# ref
# starship configuration reference: https://starship.rs/config/
# inspired by Pastel Powerline Preset: https://starship.rs/presets/pastel-powerline.html
# nerd font cheet sheet: https://www.nerdfonts.com/cheat-sheet

format = """
[](fg:1_bg)\
$os\
$username\
[](bg:2_bg fg:1_bg)\
$directory\
[](bg:3_bg fg:2_bg)\
$git_branch\
$git_status\
[](bg:4_bg fg:3_bg)\
$golang\
$python\
$haskell\
$nodejs\
$nim\
$rust\
[](bg:5_bg fg:4_bg)\
$time\
[](bg:6_bg fg:5_bg)\
$cmd_duration\
[](fg:6_bg)\
\n$character"""

# Disable the blank line at the start of the prompt
add_newline = false

palette = "eyemono"

[palettes.eyemono]
1_bg = '#DE0065'
2_bg = '#FF2883'
3_bg = '#BB2883'
4_bg = '#8340BB'
5_bg = '#4040BB'
6_bg = '#28BBBB'
1_fg = '#FFFFFF'
2_fg = '#FFFFFF'
3_fg = '#FFFFFF'
4_fg = '#FFFFFF'
5_fg = '#FFFFFF'
6_fg = '#FFFFFF'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:1_bg fg:1_fg"
style_root = "bg:1_bg fg:1_fg"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:1_bg fg:1_fg"
disabled = false                      # Disabled by default

[directory]
style = "bg:2_bg fg:2_fg"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:3_bg fg:3_fg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:3_bg fg:3_fg"
format = '[$all_status$ahead_behind]($style)'
conflicted = ' '
stashed = ' '
deleted = ' '
renamed = 'ﳳ '
modified = ' '
staged = '[$count](bg:3_bg green) '
untracked = ' '
ahead = '${count}'
behind = '${count}'
diverged = ' ${ahead_count} ${behind_count}'
up_to_date = ''

[golang]
symbol = " "
style = "bg:4_bg fg:4_fg"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:4_bg fg:4_fg"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:4_bg fg:4_fg"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:4_bg fg:4_fg"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:4_bg fg:4_fg"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:4_bg fg:4_fg"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"                        # Hour:Minute Format
style = "bg:5_bg fg:5_fg"
format = '[  $time ]($style)'

[cmd_duration]
min_time = 500
style = "bg:6_bg fg:6_fg"
format = "[ $duration ]($style)"

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
