# ref
# starship configuration reference: https://starship.rs/config/
# inspired by Pastel Powerline Preset: https://starship.rs/presets/pastel-powerline.html
# nerd font cheet sheet: https://www.nerdfonts.com/cheat-sheet

format = """
[](#DB2562)\
$os\
$username\
[](bg:#C63FCC fg:#DB2562)\
$directory\
[](fg:#C63FCC bg:#8340BB)\
$git_branch\
$git_metrics\
$git_status\
[](fg:#8340BB bg:#533FCC)\
$c\
$golang\
$haskell\
$java\
$nodejs\
$rust\
[](fg:#533FCC bg:#3F63CC)\
$docker_context\
[](fg:#3F63CC)\
$fill\
[](fg:#66EECC)\
$cmd_duration\
[](bg:#66EECC fg:#91EE99)\
$memory_usage\
[](bg:#91EE99 fg:bright-green)\
$time\
[](fg:bright-green)\
\n$character\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#DB2562 fg:bright-white"
style_root = "bg:#DB2562 fg:bright-white"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#DB2562 fg:bright-white"
disabled = true                      # Disabled by default

[directory]
style = "bg:#C63FCC fg:bright-white"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#3F63CC fg:bright-white"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#8340BB fg:bright-white"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#8340BB fg:bright-white"
format = '[$all_status $ahead_behind ]($style)'
conflicted = ''
ahead = '${count}'
behind = '${count}'
diverged = '${ahead_count}${behind_count}'
up_to_date = ''
untracked = ''
stashed = ''
modified = ''
staged = '[++\($count\)](bg:#8340BB green)'
renamed = 'ﳳ'
deleted = ''

[golang]
symbol = " "
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#533FCC fg:bright-white"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"                        # Hour:Minute Format
style = "bg:bright-green fg:white dimmed"
format = '[  $time ]($style)'

[cmd_duration]
min_time = 500
style = "bg:#66EECC fg:white dimmed"
format = "[ $duration ]($style)"

[memory_usage]
disabled = false
threshold = 0
style = "bg:#91EE99 fg:white dimmed"
format = "[  ${ram} ]($style)"

[fill]
symbol = " "
style = "fg:#ADA1AD"

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
